// <auto-generated />
using System;
using Agenda_de_produse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agenda_de_produse.Migrations
{
    [DbContext(typeof(Agenda_de_produseContext))]
    [Migration("20230112202608_Familie")]
    partial class Familie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Agenda_de_produse.Models.Familie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeFamilie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Familie");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Furnizor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeFurnizor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaraID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TaraID");

                    b.ToTable("Furnizor");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Produs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataExp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FamilieID")
                        .HasColumnType("int");

                    b.Property<int?>("FurnizorID")
                        .HasColumnType("int");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("FamilieID");

                    b.HasIndex("FurnizorID");

                    b.ToTable("Produs");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Tara", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeTara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tara");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Furnizor", b =>
                {
                    b.HasOne("Agenda_de_produse.Models.Tara", "Tara")
                        .WithMany("Furnizori")
                        .HasForeignKey("TaraID");

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Produs", b =>
                {
                    b.HasOne("Agenda_de_produse.Models.Familie", "Familie")
                        .WithMany("Produse")
                        .HasForeignKey("FamilieID");

                    b.HasOne("Agenda_de_produse.Models.Furnizor", "Furnizor")
                        .WithMany("Produse")
                        .HasForeignKey("FurnizorID");

                    b.Navigation("Familie");

                    b.Navigation("Furnizor");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Familie", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Furnizor", b =>
                {
                    b.Navigation("Produse");
                });

            modelBuilder.Entity("Agenda_de_produse.Models.Tara", b =>
                {
                    b.Navigation("Furnizori");
                });
#pragma warning restore 612, 618
        }
    }
}
